import type { NextPage } from "next";
import Head from "next/head";
import Row from "../components/Row";
import { useSession, useSupabaseClient } from "@supabase/auth-helpers-react";
import { useEffect, useState } from "react";
import { Code } from "../interfaces/Code";

const Codes: NextPage = () => {
  const supabase = useSupabaseClient();
  const [data, setData] = useState<Code[]>();

  const listCodes = async () => {
    await supabase.auth.getSession().then(async (retrievedSession) => {
      const session = retrievedSession.data.session;

      const request = await fetch("/api/list", {
        method: "POST",
        body: JSON.stringify({ session }),
      });

      setTimeout(() => {
        request.json().then((retrievedData) => {
          let reversedData = retrievedData.data.reverse();
          setData(reversedData);
        });
      }, 100);
    });
  };

  useEffect(() => {
    listCodes();
  }, [null]);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {data?.map((d, index) => (
        <Row key={index} data={d} />
      ))}
      {data?.length === 0 ? (
        <>
          <div className="my-8 py-20 sm:py-60 rounded-3xl">
            <h1 className="text-xl sm:text-5xl font-bold text-center">
              No codes created
            </h1>
          </div>
        </>
      ) : (
        ""
      )}
    </div>
  );
};

export default Codes;
