import type { NextPage } from "next";
import Head from "next/head";
import { useEffect } from "react";
import BoltIcon from "../components/Icons/BoltIcon";
import ChartIcon from "../components/Icons/ChartIcon";
import PaintBrushIcon from "../components/Icons/PaintBrushIcon";
import { useSession, useSupabaseClient } from "@supabase/auth-helpers-react";
import { useRouter } from "next/router";

const Home: NextPage = () => {
  const supabase = useSupabaseClient();
  const router = useRouter();

  useEffect(() => {
    supabase.auth.getSession().then((retrievedSession) => {
      if (retrievedSession.data.session) {
        router.push("/codes");
      }
    });
  }, [null]);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="my-8 py-20 sm:py-60 rounded-3xl">
        <h1 className="text-5xl sm:text-7xl font-bold text-center">The quick way to create a QR code</h1>
      </div>
      <div className="grid grid-cols-1 sm:grid-cols-3 sm:gap-4">
        <div className="my-4 py-20 sm:py-20 rounded-3xl bg-amber-200 text-amber-600 flex flex-col items-center">
          <ChartIcon/>
          <h1 className="text-sm sm:text-lg font-bold text-center w-44 mt-5">Create tracked and untracked QR codes</h1>
        </div>
        <div className="my-4 py-20 sm:py-20 rounded-3xl bg-blue-200 text-blue-600 flex flex-col items-center">
          <BoltIcon/>
          <h1 className="text-sm sm:text-lg font-bold text-center w-44 mt-5">Edit QR Code URL after generation</h1>
        </div>
        <div className="my-4 py-20 sm:py-20 rounded-3xl bg-green-200 text-green-600 flex flex-col items-center">
          <PaintBrushIcon/>
          <h1 className="text-sm sm:text-lg font-bold text-center w-44 mt-5">Customise your QR Code design</h1>
        </div>
      </div>
    </div>
  );
};

export default Home;
