import type { NextPage } from 'next'
import Head from 'next/head'
import Row from '../components/Row'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const data = new Array(10).fill(0);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {
        data.map((d, index) => <Row key={index}/>)
      }
    </div>
  )
}

export default Home
